apiVersion: v1
kind: ConfigMap
metadata:
  name: tester-config
data:
  redis.cluster.url.template: redis-cluster-{id}.redis-cluster-service.default.svc.cluster.local
  redis.url.single: redis-service
  redis.nodes.number: "1"
  
