apiVersion: apps/v1
kind: Deployment
metadata:
  name: tester-deployment
  labels:
    service: tester
spec:
  replicas: 1
  selector:
    matchLabels:
      service: tester
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /q/metrics
        prometheus.io/port: '80'
      labels:
        service: tester
    spec:
      containers:
      - name: tester
        image: localhost:5000/quarkus-lettuce-tester
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 4
            memory: 4Gi
          limits:
            cpu: 4
            memory: 4Gi
        env:
        - name: REDIS_URL_SINGLE
          valueFrom:
            configMapKeyRef:
              name: tester-config
              key: redis.url.single
        - name: REDIS_CLUSTER_URL_TEMPLATE
          valueFrom:
            configMapKeyRef:
              name: tester-config
              key: redis.cluster.url.template
        - name: REDIS_NODES_NUMBER
          valueFrom:
            configMapKeyRef:
              name: tester-config
              key: redis.nodes.number

