    apiVersion: v1
    kind: Service
    metadata:
      name: tester-service
      labels:
        service: tester
    spec:
      selector:
        service: tester
      ports:
      - port: 80 
        name: http
        nodePort: 30080
      type: NodePort
