    apiVersion: v1
    kind: Service
    metadata:
      name: grafana-service
      labels:
        service: grafana
    spec:
      selector:
        service: grafana
      ports:
      - port: 3000 
        name: http
        nodePort: 30003
      type: NodePort
