apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  labels:
    service: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
      service: prometheus
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '9090'
      labels:
        app: prometheus-server
        service: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
          - name: prometheus-config-volume
            mountPath: /etc/prometheus/
      volumes:
      - name: prometheus-config-volume
        configMap:
          defaultMode: 420
          name: prometheus-config
          
