    apiVersion: v1
    kind: Service
    metadata:
      name: prometheus-service
      labels:
        service: prometheus
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path:   /
        prometheus.io/port: '9090'
    spec:
      selector:
        service: prometheus
      ports:
      - port: 9090
        name: http
      type: ClusterIP
---
    apiVersion: v1
    kind: Service
    metadata:
      name: prometheus-service-np
      labels:
        service: prometheus
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path:   /
        prometheus.io/port: '9090'
    spec:
      selector:
        service: prometheus
      ports:
      - port: 9090 
        name: http
        nodePort: 30002
      type: NodePort

