    kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: grafana-pvc
      namespace: monitoring
    spec:
      storageClassName: manual
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
